---
title: Backgammon Game Class Diagram
---
classDiagram
    Users "1" --o "*" Sessions
    Users "1" --o "*" Games
    Users "1" --o "*" Tournaments
    Users "1" --o "*" Turns
    Games "1" --* "*" Turns
    Tournaments "1" --o "*" Games

    class Users {
        +SERIAL id PK
        +BPCHAR username UNIQUE
        +BPCHAR password
        +BPCHAR firstname
        +BPCHAR lastname
        +BPCHAR mail UNIQUE
        +INTEGER elo
        +BPCHAR avatar
        +BOOL is_bot DEFAULT FALSE
    }

    class Sessions {
        +SERIAL id PK
        +INTEGER user_id FK
        +TEXT token UNIQUE
        +TIMESTAMP expires_at
    }

    class Games {
        +SERIAL id PK
        +INTEGER p1_id FK
        +INTEGER p1elo
        +INTEGER p2_id FK
        +INTEGER p2elo
        +TIMESTAMP start
        +TIMESTAMP endtime
        +BPCHAR status DEFAULT 'open'
        +INTEGER[] p1checkers
        +INTEGER[] p2checkers
        +INTEGER double_value DEFAULT 1
        +BPCHAR double_owner DEFAULT 'all'
        +BOOL want_to_double DEFAULT FALSE
        +BPCHAR current_player DEFAULT 'p1'
        +INTEGER[] dices
        +INTEGER tournament FK
    }

    class Tournaments {
        +SERIAL id PK
        +BPCHAR name
        +INTEGER owner FK
        +BPCHAR status DEFAULT 'waiting'
        +INTEGER[] users
        +INTEGER[] winners DEFAULT '[]'
        +TIMESTAMP creation_date
    }

    class Turns {
        +SERIAL id PK
        +INTEGER game_id FK
        +INTEGER user_id FK
        +TIMESTAMP time
        +INTEGER[] dices
        +BOOL double
        +INTEGER[] moves
    }
