graph TD
    %% Actors
    TAdmin[Tournament Admin]
    User[User]
    Player[Player]
    Friend[Friend]

    %% Use Cases
    CreateTournament[Create Tournament]
    ManageTournament[Manage Tournament]
    TrackImprovement[Track Improvement]
    ShareProgress[Share Progress]
    ReceiveUpdates[Receive Updates]
    ManageAccount[Manage Account]
    PlayBackgammon[Play Backgammon]
    ChatPlayers[Chat with Players]
    AnalyzeGames[Analyze Games]
    AccessChallenges[Access Challenges]
    EarnBadges[Earn Digital Badges]
    ExploreThemes[Explore Graphic Themes]
    GameTree[Game Tree]

    %% Relationships
    TAdmin --> CreateTournament
    TAdmin --> ManageTournament
    
    User --> TrackImprovement
    User --> ShareProgress
    User --> ReceiveUpdates
    User --> ManageAccount
    User --> ExploreThemes
    User --> Player
    User --> TAdmin

    Player --> PlayBackgammon
    
    ShareProgress --> Friend
    
    %% Include relationships
    GameTree -.-> PlayBackgammon
    PlayBackgammon --> AnalyzeGames
    PlayBackgammon --> AccessChallenges
    PlayBackgammon --> EarnBadges
    PlayBackgammon --> ChatPlayers
    PlayBackgammon --> Bot
    CreateTournament -.-> GameTree
    ManageTournament --> Add
    Add --> Bot
    Add --> Player

    %% Styling
    classDef actor fill:#dae8fc,stroke:#6c8ebf,color:#000
    classDef useCase fill:#fff,stroke:#000,color:#000
    
    class TAdmin,User,Player,Friend,Bot,Player actor
    class CreateTournament,Add,ManageTournament,TrackImprovement,ShareProgress,ReceiveUpdates,ManageAccount,PlayBackgammon,ChatPlayers,AnalyzeGames,AccessChallenges,EarnBadges,ExploreThemes,GameTree useCase
